# Retrieve the latest stats by SSH-ing to server

# load server env variables
serverID <- Sys.getenv("SERVER_ID")
serverIP <- Sys.getenv("SERVER_IP")
serverPW <- Sys.getenv("SERVER_PW")
pathEMu <- Sys.getenv("EMU_DIR")
pathEMuMM <- Sys.getenv("EMU_DIR_MM")

# load local enviro variables
origdir <- getwd()
locEMu <- Sys.getenv("EMU_LOC")
locEMuMM <- Sys.getenv("EMU_LOC_MM") 

# # Uncomment this if testing on test-server
# pathEMu <- Sys.getenv("EMU_DIR_BOO") # "data/eaudit/"


# Create local directories for stats
if (!dir.exists(paste0(origdir, locEMu))) {
  dir.create(paste0(origdir, locEMu))
}

if (!dir.exists(paste0(origdir, locEMuMM))) {
  dir.create(paste0(origdir, locEMuMM))
}


# get data from server if running on the server

session <- ssh_connect(host = paste0(serverID, "@", serverIP),
                       verbose = 2)

## Get most recent EMu audit log
##  NOTE:
##   EMu audit logs are generated by a periodic export
##    - Monthly EMu audit log represents previous month's activity


# Download estatistics export
scp_download(session, 
             paste0(pathEMu,
                    '"$(ls ', pathEMu,
                    ' -1t --color=never | head -1)"'),
             to = paste0(origdir,locEMu))


Sys.sleep(2)

# Download emultimedia export
scp_download(session, 
             paste0(pathEMuMM,
                    '"$(ls ', pathEMuMM,
                    ' -1t --color=never | head -1)"'),
             to = paste0(origdir,locEMuMM))


Sys.sleep(2)

ssh_disconnect(session)

Sys.sleep(2)

# # output of this script should be:
# dataEMu <- "RENVIRON-VAR-path-to/latest/EMuLog.csv"
