# Import the latest logs to R
#
# Import log of EMu MM records added/edited in last month ####
# # background & alternatives here:
# # https://stackoverflow.com/questions/33446888/r-convert-xml-data-to-data-frame

## NOTE:
## pathEMu is defined in 050checkRenv.R and .Renviron

## Get most recent EMu audit log
##  REMINDER:
##   EMu audit logs are generated by a periodic export

# timeEMu <- file.info(list.files(paste(pathEMu), full.names = T))
timeEMu <- file.info(list.files(paste0(origdir, locEMu), full.names = T))

# dfEMu <- list.dirs(paste(pathEMu), full.names = T)
dfEMu <- list.dirs(paste0(origdir, locEMu), full.names = T)


if (NROW(list.dirs(paste0(origdir, locEMu))) < 1) {
  
  print(paste("no EMu audit log for", filerDate))
  write.table(print(paste("No EMu log for", filerDate)), 
              file = paste0("EMuauditErrorlog_",filerDate,".txt"))
  
} else {
  emu1 <- read.csv(paste0(dfEMu[NROW(dfEMu)], "/",
                          list.files(dfEMu[NROW(dfEMu)], pattern = "estatist")),
                   # rownames(dfEMu)[which.max(dfEMu$ctime)],
                   stringsAsFactors = F)
  
}
