# Import the latest logs to R
#
# Import log of EMu MM records added/edited in last month ####
# # background & alternatives here:
# # https://stackoverflow.com/questions/33446888/r-convert-xml-data-to-data-frame

## NOTE:
## pathEMu is defined in 050checkRenv.R and .Renviron

## Get most recent EMu stats log
##  REMINDER:
##   EMu stats logs are generated by a periodic export

# timeEMu <- file.info(list.files(paste(pathEMu), full.names = T))
timeEMu <- file.info(list.files(paste0(origdir, locEMu), full.names = T))

# dfEMu <- list.dirs(paste(pathEMu), full.names = T)
dfEMu <- list.dirs(paste0(origdir, locEMu), full.names = T)


if (NROW(list.dirs(paste0(origdir, locEMu))) < 1) {
  
  print(paste("no EMu audit log for", Sys.Date()))
  write.table(print(paste("No EMu log for", Sys.Date())), 
              file = paste0("EMuStatsErrorlog_",Sys.Date(),".txt"))
  
} else {
  emu1 <- read.csv(paste0(dfEMu[NROW(dfEMu)], "/",
                          list.files(dfEMu[NROW(dfEMu)], pattern = "estatist")),
                   # rownames(dfEMu)[which.max(dfEMu$ctime)],
                   stringsAsFactors = F)
  
}


## Get most recent EMu MM log
##  REMINDER:
##   EMu MM logs are generated by a periodic export

# timeEMu <- file.info(list.files(paste(pathEMu), full.names = T))
timeEMuMM <- file.info(list.files(paste0(origdir, locEMuMM), full.names = T))

# dfEMu <- list.dirs(paste(pathEMu), full.names = T)
dfEMuMM <- list.dirs(paste0(origdir, locEMuMM), full.names = T)


if (NROW(list.dirs(paste0(origdir, locEMuMM))) < 1) {
  
  print(paste("no EMu MM log for", Sys.Date()))
  write.table(print(paste("No EMu log for", Sys.Date())), 
              file = paste0("EMuMMErrorlog_",Sys.Date(),".txt"))
  
} else {
  emuMM <- read.csv(paste0(dfEMuMM[NROW(dfEMuMM)], "/",
                           list.files(dfEMuMM[NROW(dfEMuMM)], pattern = "MMfiles")),
                    # rownames(dfEMu)[which.max(dfEMu$ctime)],
                    stringsAsFactors = F)
  
}
